baseURL: "https://rick00kim.github.io/kururu-blog/"
defaultContentLanguage: en
languageCode: en
title: KURURU Blog
theme: FeelIt
languages:
  en:
    weight: 1
    languageCode: en
    languageName: English
    hasCJKLanguage: true
    paginate: 12
    copyright: >-
      This work is licensed under a Creative Commons Attribution-NonCommercial
      4.0 International License.
    menu:
      main:
        - identifier: posts
          pre: ""
          post: ""
          name: Posts
          url: posts/
          title: ""
          weight: 1
        - identifier: tags
          pre: ""
          post: ""
          name: Tags
          url: tags/
          title: ""
          weight: 2
        - identifier: categories
          pre: ""
          post: ""
          name: Categories
          url: categories/
          title: ""
          weight: 3
        - identifier: about
          pre: ""
          post: ""
          name: About
          url: about/
          title: ""
          weight: 5
    params:
      description: About FeelIt Theme
      keywords:
        - Theme
        - Hugo
      app:
        title: FeelIt
        noFavicon: false
        svgFavicon: ""
        themeColor: "#ffffff"
        iconColor: "#5bbad5"
        tileColor: "#da532c"
      search:
        enable: true
        type: algolia
        contentLength: 4000
        placeholder: ""
        maxResultLength: 10
        snippetLength: 30
        highlightTag: em
        absoluteURL: false
        algolia:
          index: index.en
          appID: UAL0NNJWXE
          searchKey: 7b7fbdfb7ee82ee61901f2c6b09b05be
      about:
        enable: true
        param: true
        paramTitle: SKILLS
        status:
          - faIcon: fas fa-building
            title: Company
            desc: Recurit
          - faIcon: fas fa-briefcase fa-fw
            title: Occupation
            desc: System engineer
          - title: Location
            faIcon: fas fa-map-marker-alt
            desc: Japan
        parameter:
          - language: JAVA
            level: "90"
          - language: Bash
            level: "90"
          - language: Python
            level: "80"
          - language: Javascript
            level: "70"
          - language: ReactJS
            level: "70"
      home:
        rss: 10
        profile:
          enable: true
          gravatarEmail: ""
          avatarURL: /images/avatar.webp
          title: ""
          subtitle: Happy programmer
          typeit: true
          social: true
          disclaimer: ""
        posts:
          enable: true
          paginate: 6
          imagePreview: true
params:
  version: 1.0.X
  defaultTheme: dark
  gitRepo: "https://github.com/Rick00Kim"
  page:
    toc:
      enable: true
      keepStatic: false
      auto: true
  footer:
    enable: false
  social:
    GitHub: Rick00Kim
    Linkedin: kuhyun-kim-160b9a161
    Email: dreamx119@gmail.com
markup:
  highlight:
    lineNos: true
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 4
author:
  name: Rick_Kim
  email: dreamx119@gmail.com
  link: ""
